version: '3.8'

services:
   dev-db:
      image: postgres:17-alpine
      container_name: dev-postgres
      restart: unless-stopped
      ports:
         - "5438:5432"
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: devdb
      volumes:
        - pgdata-dev:/var/lib/postgresql/data

volumes:
  pgdata-dev: